apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deploy-validate
  namespace: default
spec:
  secretName: deploy-validate-tls
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
  commonName: deploy-validate.default.svc
  dnsNames:
  - deploy-validate.default.svc
