apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-validate
  name: deploy-validate
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deploy-validate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: deploy-validate
    spec:
      containers:
      - command:
        - k8s-webhook-validate
        image: ccr.ccs.tencentyun.com/lzwk/ops-test:deploy-validate-v0.1
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8081
          name: http-check
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health_check
            port: http-check
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 4
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health_check
            port: http-check
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 4
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
      - name: qcloudregistrykey
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-validate
  name: deploy-validate
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ports:
  - name: https-443
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: deploy-validate
  sessionAffinity: None
  type: ClusterIP
